# This is a config for E2B sandbox template.
# You can use template ID (bm39oayzawiy64h94sqz) or template name (vibe-next-muadh-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-next-muadh-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-next-muadh-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-next-muadh-3')

team_id = "740d8904-27e1-4880-847b-55269a167eaa"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-next-muadh-3"
template_id = "bm39oayzawiy64h94sqz"
